# Generated by Django 3.2.13 on 2023-01-04 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CBT_attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbt_attraction', models.CharField(max_length=50, verbose_name='CBT attraction')),
            ],
        ),
        migrations.CreateModel(
            name='CBT_facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbt_facility', models.CharField(max_length=50, verbose_name='CBT Facility')),
            ],
        ),
        migrations.CreateModel(
            name='Cbt_recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbt_recommendation', models.CharField(max_length=200, verbose_name='Recommendations for CBT')),
            ],
        ),
        migrations.CreateModel(
            name='Clean_suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_suggestion', models.CharField(max_length=200, verbose_name='Clean suggestion')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=25, verbose_name='District')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=30, verbose_name='Education')),
            ],
        ),
        migrations.CreateModel(
            name='Expectation_hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expectation_hotel', models.CharField(max_length=200, verbose_name='Expectation hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Expectation_street_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expectation_street_food', models.CharField(max_length=200, verbose_name='Expectation street food')),
            ],
        ),
        migrations.CreateModel(
            name='Food_seller_recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_seller_recommendation', models.CharField(max_length=200, verbose_name='Recommendations for food seller')),
            ],
        ),
        migrations.CreateModel(
            name='Hawker_suggest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hawker_suggest', models.CharField(max_length=200, verbose_name='Suggests for hawker')),
            ],
        ),
        migrations.CreateModel(
            name='Highway_transport_dissatisfaction_reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highway_transport_dissatisfaction_reason', models.CharField(max_length=200, verbose_name='Highway transport dissatisfaction reason')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_residence_dissatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_residence_dissatisfaction', models.CharField(max_length=200, verbose_name='Hotel residence dissatisfaction')),
            ],
        ),
        migrations.CreateModel(
            name='Negative_reason_hawker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negative_reason_hawker', models.CharField(max_length=200, verbose_name='Negative reason hawker')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=30, verbose_name='Occupation')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.CharField(max_length=200, verbose_name='Opinion Level')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion_hawker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion_hawker', models.CharField(max_length=200, verbose_name='Opinion hawker')),
            ],
        ),
        migrations.CreateModel(
            name='Reason_food_dissatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_food_dissatisfaction', models.CharField(max_length=200, verbose_name='Reason food dissatisfaction')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation_improve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_improve', models.CharField(max_length=200, verbose_name='Recommendation improve')),
            ],
        ),
        migrations.CreateModel(
            name='Room_service_dissatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_service_dissatisfaction', models.CharField(max_length=200, verbose_name='Reason of room service dissatisfaction')),
            ],
        ),
        migrations.CreateModel(
            name='Safety_issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_issue', models.CharField(max_length=200, verbose_name='Safety issue')),
            ],
        ),
        migrations.CreateModel(
            name='Safety_recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_recommendation', models.CharField(max_length=200, verbose_name='Recommendations for safety & security')),
            ],
        ),
        migrations.CreateModel(
            name='Satisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction', models.CharField(max_length=30, verbose_name='Satisfaction level')),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=15, verbose_name='Sex')),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot', models.CharField(max_length=50, verbose_name='Spot')),
            ],
        ),
        migrations.CreateModel(
            name='Spot_expectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_expectation', models.CharField(max_length=100, verbose_name='Spot expectation')),
            ],
        ),
        migrations.CreateModel(
            name='Tour_operator_dissatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_operator_dissatisfaction', models.CharField(max_length=200, verbose_name='Reason behind dissatisfaction on tour operator')),
            ],
        ),
        migrations.CreateModel(
            name='Tour_operator_recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_operator_recommendation', models.CharField(max_length=200, verbose_name='Recommendations for Tour operator')),
            ],
        ),
        migrations.CreateModel(
            name='Tour_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(max_length=50, verbose_name='Tour type')),
            ],
        ),
        migrations.CreateModel(
            name='Tourist_police_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourist_police_services', models.CharField(max_length=200, verbose_name='Services of tourist police')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.CharField(max_length=30, verbose_name='Transport')),
            ],
        ),
        migrations.CreateModel(
            name='Transport_dissatisfaction_reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_dissatisfaction_reason', models.CharField(max_length=200, verbose_name='Transport dissatisfaction reason')),
            ],
        ),
        migrations.CreateModel(
            name='Transport_manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_manage', models.CharField(max_length=100, verbose_name='Transport manage')),
            ],
        ),
        migrations.CreateModel(
            name='Transport_recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_recommendation', models.CharField(max_length=200, verbose_name='Recommendations for transport')),
            ],
        ),
        migrations.CreateModel(
            name='Travel_interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_interest', models.CharField(max_length=50, verbose_name='Travel interest')),
            ],
        ),
        migrations.CreateModel(
            name='Travel_season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_season', models.CharField(max_length=15, verbose_name='Travel season')),
            ],
        ),
        migrations.CreateModel(
            name='Vacation_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_package', models.CharField(max_length=50, verbose_name='Vacation package offers')),
            ],
        ),
        migrations.CreateModel(
            name='Yes_no',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_no', models.CharField(max_length=10, verbose_name='Yes or No')),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1_name', models.CharField(max_length=30, verbose_name='Tourist name')),
                ('a2_age', models.IntegerField(blank=True, verbose_name='Age')),
                ('a6_mobile', models.CharField(blank=True, max_length=15, verbose_name='Mobile')),
                ('a7_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address')),
                ('a12_yearly_travel', models.IntegerField(blank=True, null=True, verbose_name='Average travel day in a year')),
                ('a10_travel_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.travel_interest')),
                ('a11_season_choices', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.travel_season')),
                ('a3_gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.sex')),
                ('a4_occupation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.occupation')),
                ('a5_education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.education')),
                ('a8_home_dist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.district')),
                ('a9_tour_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.tour_type')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, verbose_name='Name')),
                ('b3', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='B3_Do you know about community based tourism?')),
                ('b4', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='B4_(If b3 is yes) Do you think community based tourism need to be started in here?')),
                ('b5', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='B5_(If b3 is yes) Will you visit any community if community based tourism is started?')),
                ('b6_1', models.CharField(blank=True, max_length=500, null=True, verbose_name='B6_1_(If b3 is yes) Others (What you want to see during community visit which will attract you?)')),
                ('b7_1', models.CharField(blank=True, max_length=500, null=True, verbose_name='B7_1_(If b3 is yes) Others (Which facilities you expect during community visit?)')),
                ('b8_1', models.CharField(blank=True, max_length=500, null=True, verbose_name='B8_1_(If b3 is yes) Others (What are your recommendations to improve community based tourism?)')),
                ('b1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visited_dist', to='dash.district', verbose_name='B1_  Select your visited district')),
                ('b2', models.ManyToManyField(blank=True, to='dash.Spot', verbose_name='B2_Which tourist spots you visited?')),
                ('b6', models.ManyToManyField(blank=True, to='dash.CBT_attraction', verbose_name='B6_(If b3 is yes) What you want to see during community visit which will attract you?')),
                ('b7', models.ManyToManyField(blank=True, to='dash.CBT_facility', verbose_name='B7_(If b3 is yes) Which facilities you expect during community visit?')),
                ('b8', models.ManyToManyField(blank=True, to='dash.Cbt_recommendation', verbose_name='B8_(If b3 is yes) What are your recommendations to improve community based tourism?')),
            ],
        ),
    ]
