# Generated by Django 3.2.13 on 2022-12-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CBT_attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbt_attraction', models.CharField(max_length=15, verbose_name='CBT attraction')),
            ],
        ),
        migrations.CreateModel(
            name='CBT_facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbt_facility', models.CharField(max_length=15, verbose_name='CBT Facility')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=15, verbose_name='District')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=15, verbose_name='Education')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b1_visited_dist', models.CharField(blank=True, max_length=30, verbose_name='District')),
                ('b21_2_spot', models.CharField(blank=True, max_length=30, verbose_name='Spot')),
                ('b2_cbt_known', models.BooleanField(verbose_name='b2_cbt_known')),
                ('b3_cbt_need', models.BooleanField(verbose_name='b3_cbt_need')),
                ('b4_cbt_visit', models.BooleanField(verbose_name='b4_cbt_visit')),
                ('b5_cbt_attraction', models.CharField(blank=True, max_length=30, verbose_name='Your CBT Attractions')),
                ('b6_cbt_facility', models.CharField(blank=True, max_length=30, verbose_name='b6_cbt_facility')),
                ('b7_vacation_package', models.CharField(blank=True, max_length=30, verbose_name='b7_vacation_package')),
                ('b8_tour_operator', models.BooleanField(verbose_name='b8_tour_operator')),
                ('b9_tour_operator_ev', models.IntegerField(verbose_name='b9_tour_operator_ev')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=15, verbose_name='Occupation')),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=15, verbose_name='Sex')),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot', models.CharField(max_length=15, verbose_name='Spot')),
                ('district2', models.CharField(max_length=15, verbose_name='District')),
            ],
        ),
        migrations.CreateModel(
            name='Tour_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(max_length=30, verbose_name='Tour type')),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1_name', models.CharField(max_length=30, verbose_name='Tourist name')),
                ('a2_age', models.IntegerField(blank=True, verbose_name='Age')),
                ('a3_gender', models.CharField(blank=True, max_length=30, verbose_name='Gender')),
                ('a4_occupation', models.CharField(blank=True, max_length=30, verbose_name='Occupation')),
                ('a5_education', models.CharField(blank=True, max_length=30, verbose_name='Education')),
                ('a6_mobile', models.CharField(blank=True, max_length=15, verbose_name='Mobile')),
                ('a7_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address')),
                ('a8_home_dist', models.CharField(blank=True, max_length=30, verbose_name='District')),
                ('a9_tour_type', models.CharField(blank=True, max_length=30, verbose_name='Tour type')),
                ('a10_travel_interest', models.CharField(blank=True, max_length=30, verbose_name='Travel interest')),
                ('a11_season_choices', models.CharField(blank=True, max_length=30, verbose_name='Season prefer')),
                ('a12_yearly_travel', models.IntegerField(blank=True, null=True, verbose_name='Average travel day in a year')),
            ],
        ),
        migrations.CreateModel(
            name='Travel_interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_interest', models.CharField(max_length=30, verbose_name='Travel interest')),
            ],
        ),
        migrations.CreateModel(
            name='Travel_season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_season', models.CharField(max_length=15, verbose_name='Travel season')),
            ],
        ),
        migrations.CreateModel(
            name='Vacation_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_package', models.CharField(max_length=15, verbose_name='Vacation package offers')),
            ],
        ),
    ]
