# Generated by Django 3.2.13 on 2023-01-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBT_rec1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbt_rec1', models.CharField(max_length=300, verbose_name='CBT recommendation')),
            ],
        ),
        migrations.AlterField(
            model_name='survey',
            name='b8',
            field=models.ManyToManyField(blank=True, to='dash.CBT_rec1', verbose_name='B8_(If b3 is yes) What are your recommendations to improve community based tourism?'),
        ),
    ]
