# Generated by Django 3.2.13 on 2022-12-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction', models.CharField(max_length=30, verbose_name='Vacation package offers')),
            ],
        ),
        migrations.CreateModel(
            name='Yes_no',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_no', models.CharField(max_length=10, verbose_name='Yes or No')),
            ],
        ),
        migrations.RemoveField(
            model_name='spot',
            name='district2',
        ),
        migrations.AlterField(
            model_name='spot',
            name='spot',
            field=models.CharField(max_length=30, verbose_name='Vacation package offers'),
        ),
    ]
