# Generated by Django 3.2.13 on 2023-01-01 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='b1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visited_dist', to='dash.district'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='b3',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Do you know about community based tourism?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='b4',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Do you know about community based tourism?'),
        ),
    ]
