# Generated by Django 3.2.13 on 2022-12-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20221227_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='yes_no',
            name='code_11',
            field=models.IntegerField(null=True, unique=True, verbose_name='Code'),
        ),
    ]
