# Generated by Django 3.2.13 on 2023-01-01 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20230101_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='b1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visited_dist', to='dash.district', verbose_name='Spot'),
        ),
    ]
