# Generated by Django 3.2.13 on 2022-12-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_yes_no_code_11'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clean_suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_suggestion', models.CharField(max_length=30, verbose_name='Clean suggestion')),
            ],
        ),
        migrations.CreateModel(
            name='Expectation_hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expectation_hotel', models.CharField(max_length=30, verbose_name='Expectation hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Expectation_street_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expectation_street_food', models.CharField(max_length=30, verbose_name='Expectation street food')),
            ],
        ),
        migrations.CreateModel(
            name='Negative_reason_hawker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negative_reason_hawker', models.CharField(max_length=200, verbose_name='Negative reason hawker')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.CharField(max_length=30, verbose_name='Opinion Level')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion_hawker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion_hawker', models.CharField(max_length=200, verbose_name='Opinion hawker')),
            ],
        ),
        migrations.CreateModel(
            name='Reason_food_dissatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_food_dissatisfaction', models.CharField(max_length=30, verbose_name='Reason food dissatisfaction')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation_improve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_improve', models.CharField(max_length=200, verbose_name='Recommendation improve')),
            ],
        ),
        migrations.CreateModel(
            name='Safety_issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_issue', models.CharField(max_length=30, verbose_name='Safety issue')),
            ],
        ),
        migrations.CreateModel(
            name='Spot_expectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_expectation', models.CharField(max_length=30, verbose_name='Spot expectation')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.CharField(max_length=30, verbose_name='Transport')),
            ],
        ),
        migrations.CreateModel(
            name='Transport_dissatisfaction_reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_dissatisfaction_reason', models.CharField(max_length=200, verbose_name='Transport dissatisfaction reason')),
            ],
        ),
        migrations.CreateModel(
            name='Transport_manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_manage', models.CharField(max_length=100, verbose_name='Transport manage')),
            ],
        ),
        migrations.RemoveField(
            model_name='yes_no',
            name='code_11',
        ),
    ]
