# Generated by Django 3.2.13 on 2023-01-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20230104_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='d10',
            field=models.ManyToManyField(blank=True, to='dash.Expectation_street_food', verbose_name='D10_ What you expect from street food sellers during food serving?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d10_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='D10_1_ Other expectations on street food'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d11',
            field=models.ManyToManyField(blank=True, to='dash.Food_seller_recommendation', verbose_name='D11_ What is your recommendation to increase the skill of food seller?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d11_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='D11_1_ Others (What is your recommendation to increase the skill of food seller?)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d4',
            field=models.CharField(blank=True, choices=[('Very satisfied', 'Very satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very dissatisfied', 'Very dissatisfied')], max_length=500, verbose_name='D4_Are you satisfied with hotel residence system in tourist spot?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d5',
            field=models.ManyToManyField(blank=True, to='dash.Hotel_residence_dissatisfaction', verbose_name='D5_(If d4 is dissatisfaction) Reason behind dissatisfation'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d5_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='D5_1_(If d4 is dissatisfaction) Others (Reason behind dissatisfation)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d6',
            field=models.ManyToManyField(blank=True, to='dash.Expectation_hotel', verbose_name='D6_What is your recommendations for hotel service?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d6_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='D6_1_Other ( What is your recommendations for hotel service?)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d7',
            field=models.CharField(blank=True, choices=[('Very satisfied', 'Very satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very dissatisfied', 'Very dissatisfied')], max_length=30, verbose_name='D7_Are you satisfied with the food of restaurant?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d8',
            field=models.ManyToManyField(blank=True, to='dash.Reason_food_dissatisfaction', verbose_name='D8_(If d7 is dissatisfaction) Reason behind dissatisfation'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d8_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='D8_1_(If d7 is dissatisfaction) Others (Reason behind dissatisfation)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d9',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='D9_ Do you like street food of tourist spots?'),
        ),
    ]
