# Generated by Django 3.2.13 on 2023-01-01 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_alter_survey_b1'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='b5',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='(If b3 is yes) Will you visit any community if community based tourism is started?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='b1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visited_dist', to='dash.district', verbose_name='Select your visited district'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='b2',
            field=models.ManyToManyField(blank=True, to='dash.Spot', verbose_name='Which tourist spots you visited?'),
        ),
    ]
