# Generated by Django 3.2.13 on 2023-01-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20230101_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='b6',
            field=models.ManyToManyField(blank=True, to='dash.CBT_attraction', verbose_name='(If b3 is yes) What you want to see during community visit which will attract you?'),
        ),
    ]
