# Generated by Django 3.2.13 on 2023-01-04 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20230104_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='e1',
            field=models.ManyToManyField(blank=True, to='dash.Transport', verbose_name='E1_ What transport you used to travel?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e1_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='E1_1_ Mention other transport'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e2',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='E2_Have you managed your transport by own to come here?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.transport_manage', verbose_name='E3_ How you have managed transport?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e3_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='E3_1_ Mention other process'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e4',
            field=models.CharField(blank=True, choices=[('Very satisfied', 'Very satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very dissatisfied', 'Very dissatisfied')], max_length=200, verbose_name='E4_ Are you satisfied with the highway transport system?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e5',
            field=models.ManyToManyField(blank=True, to='dash.Highway_transport_dissatisfaction_reason', verbose_name='E5_(If e4 is dissatisfaction) Reason behind dissatisfation'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e5_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='E5_1_(If e4 is dissatisfaction) Others (Reason behind dissatisfation)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e6',
            field=models.CharField(blank=True, choices=[('Very satisfied', 'Very satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very dissatisfied', 'Very dissatisfied')], max_length=30, verbose_name='E6_Are you satisfied with the internal transport (tomtom/riksha) of this area?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e7',
            field=models.ManyToManyField(blank=True, to='dash.Transport_dissatisfaction_reason', verbose_name='E7_(If e6 is dissatisfaction) Reason behind dissatisfation'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e7_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='E7_1_(If e6 is dissatisfaction) Others (Reason behind dissatisfation)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e8',
            field=models.ManyToManyField(blank=True, to='dash.Transport_recommendation', verbose_name='E8_ What is your recommendation to increase the skill of tomtom/riksha driver?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e8_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='E8_1_ Others (What is your recommendation to increase the skill of tomtom/riksha driver?)'),
        ),
    ]
