# Generated by Django 3.2.13 on 2023-01-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_survey_b6'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='b6_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='(If b3 is yes) Others (What you want to see during community visit which will attract you?)'),
        ),
    ]
