# Generated by Django 3.2.13 on 2023-01-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_auto_20230104_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='f1',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='F1_ Do you like midnight travelling?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='f2',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='F2_ Do you think this place is safe for midnight visiting?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='f3',
            field=models.CharField(blank=True, choices=[('Very satisfied', 'Very satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very dissatisfied', 'Very dissatisfied')], max_length=30, verbose_name='F3_Are you satisfied the security of this place?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='f4',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='F4_ Have you ever harrassed by local people?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='f5',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='F5_ Have you ever faced any problem during visiting tourist spot?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='f6',
            field=models.ManyToManyField(blank=True, to='dash.Safety_issue', verbose_name='F6_(If f4 or f5 yes) What type of problems you faced?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='f6_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='F6_1_ Other problems'),
        ),
        migrations.AddField(
            model_name='survey',
            name='f7',
            field=models.ManyToManyField(blank=True, to='dash.Safety_recommendation', verbose_name='F7_ How do you think these problem can be solved?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='f7_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='F7_1_ Others (How do you think these problem can be solved?)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='h1',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='H1_ Do you know about the activity of tourist police?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='h2',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='H2_ Do you ever received any service from tourist police?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='h3',
            field=models.ManyToManyField(blank=True, to='dash.Tourist_police_services', verbose_name='H3_(If h2 is yes) What type of service you received?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='h3_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name=''),
        ),
    ]
