# Generated by Django 3.2.13 on 2023-01-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_survey_b6_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='b7',
            field=models.ManyToManyField(blank=True, to='dash.CBT_facility', verbose_name='(If b3 is yes) Which facilities you expect during community visit?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='b7_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='(If b3 is yes) Others (Which facilities you expect during community visit?)'),
        ),
    ]
