# Generated by Django 3.2.13 on 2023-01-01 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_auto_20230101_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='c1',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='C1_Have you received service from tour operator?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='c2',
            field=models.CharField(blank=True, choices=[('Very satisfied', 'Very satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very dissatisfied', 'Very dissatisfied')], max_length=20, verbose_name='C1_Have you received service from tour operator?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='b1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visited_dist', to='dash.district', verbose_name='B1_  Select your visited district'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='b2',
            field=models.ManyToManyField(blank=True, to='dash.Spot', verbose_name='B2_Which tourist spots you visited?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='b3',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='B3_Do you know about community based tourism?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='b4',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='B4_Do you know about community based tourism?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='b5',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='B5_(If b3 is yes) Will you visit any community if community based tourism is started?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='b6',
            field=models.ManyToManyField(blank=True, to='dash.CBT_attraction', verbose_name='B6_(If b3 is yes) What you want to see during community visit which will attract you?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='b6_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='B6_1_(If b3 is yes) Others (What you want to see during community visit which will attract you?)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='b7',
            field=models.ManyToManyField(blank=True, to='dash.CBT_facility', verbose_name='B7_(If b3 is yes) Which facilities you expect during community visit?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='b7_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='B7_1_(If b3 is yes) Others (Which facilities you expect during community visit?)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='b8',
            field=models.ManyToManyField(blank=True, to='dash.Cbt_Recommendation', verbose_name='B8_(If b3 is yes) What are your recommendations to improve community based tourism?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='b8_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='B8_1_(If b3 is yes) Others (What are your recommendations to improve community based tourism?)'),
        ),
    ]
