# Generated by Django 3.2.13 on 2023-01-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_alter_survey_c2'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='name',
            field=models.CharField(blank=True, max_length=10, verbose_name='Name'),
        ),
    ]
