# Generated by Django 3.2.13 on 2023-01-01 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0012_auto_20230101_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='c4',
            field=models.ManyToManyField(blank=True, to='dash.Vacation_package', verbose_name='C4_As a tourist, what you want in a vacation package?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='c4_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='C4_1_Others (As a tourist, what you want in a vacation package?)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='c5',
            field=models.ManyToManyField(blank=True, to='dash.Tour_operator_recommendation', verbose_name='C5_What are your recommendations for tour operators?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='c5_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='C5_1_ Others (What are your recommendations for tour operators?)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.opinion', verbose_name='D1_What is your opinion on the cost of hotel in tourist spots?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d2',
            field=models.CharField(blank=True, choices=[('Very satisfied', 'Very satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very dissatisfied', 'Very dissatisfied')], max_length=30, verbose_name='D2_Are you satisfied with hotel room service?'),
        ),
    ]
