# Generated by Django 3.2.13 on 2023-01-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0013_auto_20230101_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='d3',
            field=models.ManyToManyField(blank=True, to='dash.Room_service_dissatisfaction', verbose_name='D3_(If d2 is dissatisfaction) Reason behind dissatisfation'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d3_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='D3_1_Others (What are your recommendations for tour operators?)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d4',
            field=models.CharField(blank=True, choices=[('Very satisfied', 'Very satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very dissatisfied', 'Very dissatisfied')], max_length=500, verbose_name='D4_Are you satisfied with hotel residence system in tourist spot?'),
        ),
    ]
