# Generated by Django 3.2.13 on 2023-01-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0014_auto_20230101_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='d5',
            field=models.ManyToManyField(blank=True, to='dash.Hotel_residence_dissatisfaction', verbose_name='D5_(If d4 is dissatisfaction) Reason behind dissatisfation'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d5_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='D5_1_(If d4 is dissatisfaction) Others (Reason behind dissatisfation)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d6',
            field=models.ManyToManyField(blank=True, to='dash.Expectation_hotel', verbose_name='D6_What is your recommendations for hotel service?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d6_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='D6_1_Other ( What is your recommendations for hotel service?)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d7',
            field=models.CharField(blank=True, choices=[('Very satisfied', 'Very satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very dissatisfied', 'Very dissatisfied')], max_length=30, verbose_name='D7_Are you satisfied with the food of restaurant?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d8',
            field=models.ManyToManyField(blank=True, to='dash.Reason_food_dissatisfaction', verbose_name='D8_(If d7 is dissatisfaction) Reason behind dissatisfation'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d8_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='D8_1_(If d7 is dissatisfaction) Others (Reason behind dissatisfation)'),
        ),
    ]
