# Generated by Django 3.2.13 on 2023-01-01 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0015_auto_20230101_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hawker_suggest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hawker_suggest', models.CharField(max_length=200, verbose_name='Suggests for hawker')),
            ],
        ),
        migrations.CreateModel(
            name='Highway_transport_dissatisfaction_reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highway_transport_dissatisfaction_reason', models.CharField(max_length=200, verbose_name='Highway transport dissatisfaction reason')),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='d10',
            field=models.ManyToManyField(blank=True, to='dash.Expectation_street_food', verbose_name='D10_ What you expect from street food sellers during food serving?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d10_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='D10_1_ Other expectations on street food'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d11',
            field=models.ManyToManyField(blank=True, to='dash.Food_seller_recommendation', verbose_name='D11_ What is your recommendation to increase the skill of food seller?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d11_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='D11_1_ Others (What is your recommendation to increase the skill of food seller?)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='d9',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='D9_ Do you like street food of tourist spots?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e1',
            field=models.ManyToManyField(blank=True, to='dash.Transport', verbose_name='E1_ What transport you used to travel?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e1_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='E1_1_ Mention other transport'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e2',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='E2_Have you managed your transport by own to come here?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.transport_manage', verbose_name='E3_ How you have managed transport?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e3_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='E3_1_ Mention other process'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e4',
            field=models.CharField(blank=True, choices=[('Very satisfied', 'Very satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very dissatisfied', 'Very dissatisfied')], max_length=200, verbose_name='E4_ Are you satisfied with the highway transport system?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e5_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='E5_1_(If e4 is dissatisfaction) Others (Reason behind dissatisfation)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e6',
            field=models.CharField(blank=True, choices=[('Very satisfied', 'Very satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very dissatisfied', 'Very dissatisfied')], max_length=30, verbose_name='E6_Are you satisfied with the internal transport (tomtom/riksha) of this area?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e7',
            field=models.ManyToManyField(blank=True, to='dash.Transport_dissatisfaction_reason', verbose_name='E7_(If e6 is dissatisfaction) Reason behind dissatisfation'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e7_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='E7_1_(If e6 is dissatisfaction) Others (Reason behind dissatisfation)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e8',
            field=models.ManyToManyField(blank=True, to='dash.Transport_recommendation', verbose_name='E8_ What is your recommendation to increase the skill of tomtom/riksha driver?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e8_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='E8_1_ Others (What is your recommendation to increase the skill of tomtom/riksha driver?)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='f1',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='F1_ Do you like midnight travelling?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='f2',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='F2_ Do you think this place is safe for midnight visiting?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='f3',
            field=models.CharField(blank=True, choices=[('Very satisfied', 'Very satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very dissatisfied', 'Very dissatisfied')], max_length=30, verbose_name='F3_Are you satisfied the security of this place?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='f4',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='F4_ Have you ever harrassed by local people?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='f5',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='F5_ Have you ever faced any problem during visiting tourist spot?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='f6',
            field=models.ManyToManyField(blank=True, to='dash.Safety_issue', verbose_name='F6_(If f4 or f5 yes) What type of problems you faced?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='f6_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='F6_1_ Other problems'),
        ),
        migrations.AddField(
            model_name='survey',
            name='f7',
            field=models.ManyToManyField(blank=True, to='dash.Safety_recommendation', verbose_name='F7_ How do you think these problem can be solved?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='f7_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='F7_1_ Others (How do you think these problem can be solved?)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='g1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.opinion_hawker', verbose_name='G1_What is your opinion on presence of hawker in tourist spot?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='g2',
            field=models.ManyToManyField(blank=True, to='dash.Negative_reason_hawker', verbose_name='G2_(If g1 is negative) Reasons behind negative opinion'),
        ),
        migrations.AddField(
            model_name='survey',
            name='g2_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='G2_1_ Other (Reasons behind negative opinion)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='g3',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='G3_ Do you think rehabilitation of hawkers is necessary?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='g4_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='G4_1_ Others ( What are your recommendations to increase the skill of hawkers?)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='h1',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='H1_ Do you know about the activity of tourist police?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='h2',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='H2_ Do you ever received any service from tourist police?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='h3',
            field=models.ManyToManyField(blank=True, to='dash.Tourist_police_services', verbose_name='H3_(If h2 is yes) What type of service you received?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='h3_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='survey',
            name='i1',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='I1_Do you think this tourist spot is cleaned enough?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='i2',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='I2_Do you think you are cooperating to clean this area?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='i3',
            field=models.ManyToManyField(blank=True, to='dash.Clean_suggestion', verbose_name='I3_ What is your recemmendation to clean this area?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='i3_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='I3_1_ Others'),
        ),
        migrations.AddField(
            model_name='survey',
            name='k1',
            field=models.ManyToManyField(blank=True, to='dash.Spot_expectation', verbose_name='K1_What you expect from tourist spot?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='k1_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='K1_1_ Others ( What you expect from tourist spot?)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='k2',
            field=models.ManyToManyField(blank=True, to='dash.Recommendation_improve', verbose_name='K2_How tourism sector can be developed according to you?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='k2_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='K2_1_ Other ( How tourism sector can be developed according to you?)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='e5',
            field=models.ManyToManyField(blank=True, to='dash.Highway_transport_dissatisfaction_reason', verbose_name='E5_(If e4 is dissatisfaction) Reason behind dissatisfation'),
        ),
        migrations.AddField(
            model_name='survey',
            name='g4',
            field=models.ManyToManyField(blank=True, to='dash.Hawker_suggest', verbose_name='G4_ What are your recommendations to increase the skill of hawkers?'),
        ),
    ]
